{% set name = "libxkbfile" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name }}-{{ version }}.tar.xz
  sha256: 7f71884e5faf56fb0e823f3848599cf9b5a9afce51c90982baeb64f635233ebf

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libxkbfile', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - xorg-libx11
    - xorg-xorgproto
    - pthread-stubs

test:
  commands:
    - test -f "${PREFIX}/lib/libxkbfile${SHLIB_EXT}"

about:
  home: https://www.x.org/wiki/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Parses the XKB configuration data files'
  doc_url: https://www.x.org/wiki/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxkbfile

extra:
  recipe-maintainers:
    - scopatz
    - erykoff
    - hmaarrfk
