travis:
  secure:
    BINSTAR_TOKEN: fHPk2jy2M+YwpgUbwumqOGziAq8w0d9dyC5sGM6HibBp08jE3XsB0jl6MaFThJdp5IYZVl9ScpsTIgASOR59qBdvlXiniHl/3+q8ncKDTrgVFP9/oyCD6V3ZsXtuPeRv8YOiWYW7+AtLvw6kkfaKNTI3dnOHc/SEnLC3a5mwlOCY6vGRA2ZMftOhN+gsGYderyYgxsr+6EjwWxrD/E3XDQrXduHPRAvYnia9ZdvuX+SXf+LdahRU8y/pQL06c0mLmsWKG4kXlHw7ogBjJZj4e+95BeTl23gbBjrhIl7eW2GhpjJY/a8SJHcLgs/z8j/tPYMgPsE9D/6XEKJcEUUaWPueDTYpqKQ/w5wKinrIIjFd7CbLPRFR0HBocl3wnihzqwH6ggVAuwg0otM8sfO0mAlK1Rj29yn+CnAzJd+zyA6fHZvGT8GpHaL9f1GHE6ey6MJ3JyaID21NTefe19tjOCgFDzFQjxpz27K3DkRfoWpEj3+0cjBn5Hw2VJaAGLq5jpbVlEBLR4trIHFlSLMZgDe9jdqUcNgFxP9uJlNLknHdgmYqJzgqs5s/SdrI26qzjH74URMdFnOW9fOOVA9BQ8Yjo9V+lex/tRXRhNOMjoUY4TpeCZQGxzYaQw2+DosUCtxJrQ2rM/M2ZDbPMKEb8tFs83FhdkGJZfNNd5CKgXU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
